spm_model: joint_spm.model  
manifest: manifest_joint.tsv 

audio:
  sample_rate: 16000
  min_duration: 1.0

train:
  batch_size: 16
  num_workers: 4
  epochs: 10
  grad_accum: 1
  mixed_precision: false

optim:
  lr: 2e-4
  weight_decay: 1e-2
  betas: [0.9, 0.98]

model:
  hidden_dim: 256
  proj_dim: 256
  n_layers: 4

paths:
  out_dir: ./checkpoints
  log_dir: ./logs
